chat/urls.py
from django.contrib.auth import views
from django.urls import path, re_path


from .views import ThreadView, OnlineUsers
#from django.contrib.auth import  views as auth_views

app_name = 'chat'

urlpatterns = [
    path("", OnlineUsers, name="online"),
    #re_path(r"^(?P<username>[\w.@+-]+)", ThreadView.as_view(),name='second'),
    path("<username>/", ThreadView.as_view(),name='second'),
]

chatsystem/urls.py
from os import name
from django.contrib import admin
from django.urls import path , include
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView
#from chat.views import new_user

urlpatterns = [
    path('', TemplateView.as_view(template_name="home.html"),name='home'),
    path('admin/', admin.site.urls),
    path("login/", auth_views.LoginView.as_view(template_name = 'registration/login.html'), name='login'),
    path("logout/", auth_views.LogoutView.as_view(), name='logout'),
    path('messages/', include('chat.urls')),
    #path('users/', new_user, name='new_user'),
]

chat/models.py
from django.db import models

from django.conf import settings
from django.db import models
from django.db.models import Q


class ThreadManager(models.Manager):


    def get_or_new(self, user, other_username): # get_or_create
        username = user.username
        if username == other_username:
            return None
        qlookup1 = Q(first__username=username) & Q(second__username=other_username)
        qlookup2 = Q(first__username=other_username) & Q(second__username=username)
        qs = self.get_queryset().filter(qlookup1 | qlookup2).distinct()
        if qs.count() == 1:
            return qs.first(), False
        elif qs.count() > 1:
            return qs.order_by('timestamp').first(), False
        else:
            Klass = user.__class__
            user2 = Klass.objects.get(username=other_username)
            if user != user2:
                obj = self.model(
                        first=user, 
                        second=user2
                    )
                obj.save()
                return obj, True
            return None, False


class Thread(models.Model):
    first        = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='chat_thread_first')
    second       = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='chat_thread_second')
    updated      = models.DateTimeField(auto_now=True)
    timestamp    = models.DateTimeField(auto_now_add=True)
    
    objects      = ThreadManager()

   

class ChatMessage(models.Model):
    thread      = models.ForeignKey(Thread, null=True, blank=True, on_delete=models.SET_NULL)
    user        = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='sender', on_delete=models.CASCADE)
    message     = models.TextField()
    timestamp   = models.DateTimeField(auto_now_add=True)

chat/forms.py
from django import forms


class ComposeForm(forms.Form):
    message = forms.CharField(
            widget=forms.TextInput(
                attrs={"class": "form-control"}
                )
            )

chat/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import Http404, HttpResponseForbidden
from django.http import request
from django.shortcuts import render
from django.urls import reverse
from django.views.generic.edit import FormMixin

from django.views.generic import DetailView, ListView

from .forms import ComposeForm
from .models import Thread, ChatMessage
from django.contrib.auth.decorators import login_required

from django.contrib.auth.models import User
from django.contrib.auth import get_user_model
from online_users.models import OnlineUserActivity
from datetime import timedelta

@login_required
def OnlineUsers(request):
    user_activity_objects = OnlineUserActivity.get_user_activities(timedelta(minutes=3))
    number_of_active_users = user_activity_objects.count()

    online_users = user_activity_objects
    current_user = get_user_model()

    return render(request,'chat/online.html',{"online_users":online_users , "current_user": current_user})

class ThreadView(LoginRequiredMixin, FormMixin, DetailView):
    template_name = 'chat/thread.html'
    form_class = ComposeForm
    success_url = './'

    def get_queryset(self):
        return Thread.objects.by_user(self.request.user)

    def get_object(self):
        other_username  = self.kwargs.get("username")
        obj, created    = Thread.objects.get_or_new(self.request.user, other_username)
        if obj == None:
            raise Http404
        return obj

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = self.get_form()
        return context

    def post(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return HttpResponseForbidden()
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        thread = self.get_object()
        user = self.request.user
        message = form.cleaned_data.get("message")
        ChatMessage.objects.create(user=user, thread=thread, message=message)
        return super().form_valid(form)

chat/templates/chat/online.html
{% extends "base.html" %}

{% block content %}

<div>
    <p>Click the other User with whom you wanna chat to!</p>
<ul class="list-group">
{% for online_user in online_users %}
    
  <li class="list-group-item"> <a class="btn btn-primary" href="{% url 'chat:second' username=online_user.user %}"> {{online_user.user}} </a> <i class="fas fa-globe-europe"></i> <i> &emsp; last seen: </i>{{online_user.last_activity}} </li>
  
{% endfor %}
</ul>
</div>


{% endblock %}

chat/templates/chat/thread.html
{% extends "base.html" %}

{% block content %}
<h3>Chat for {% if user != object.first %}{{ object.first }}{% else %}{{ object.second }}{% endif %}</h3>
<ul id='chat-items' class="list-group">
{% for chat in object.chatmessage_set.all %}

<li class="list-group-item"> <i> { {{ chat.user }} } </i>: {{ chat.message }} </li>

{% endfor %}
</ul>

<form id='form' method='POST'> {% csrf_token %}
{{form.as_p }}
<input type="hidden" id="myUsername" value={{user.username}}>
<input type='submit' class='btn btn-primary'/>
</form>

{% endblock %}

{% block script %}

<script src = "https://cdnjs.cloudflare.com/ajax/libs/reconnecting-websocket/1.0.0/reconnecting-websocket.min.js"></script>

<script>
// websocket scripts
//console.log(window.location)
var loc = window.location
var formData = $("#form")
var msgInput = $("#id_message")
var chatHolder = $("#chat-items")
var me = $("#myUsername").val()
var wsStart = 'ws://' 
if (loc.protocol == 'https:'){
    wsStart = 'wss://' 
    }
var endpoint = wsStart+loc.host+loc.pathname
var socket = new ReconnectingWebSocket(endpoint)

socket.onmessage = function(e){
    console.log("message", e)
    //console.log(e.data)
    var chatDataMsg = JSON.parse(e.data)
    chatHolder.append("<li class='list-group-item'><i>{ "+ chatDataMsg.username+" } </i> :" + chatDataMsg.message +"</li>")
}
socket.onopen = function(e){
    console.log("open", e)
    formData.submit(function(event){
        event.preventDefault()
        var msgText = msgInput.val()
        //chatHolder.append("<li>"+ msgText +" via "+ me +"</li>")
        //var formDataserialized = formData.serialize()
        var finalData = {
            'message':msgText
        }
        socket.send(JSON.stringify(finalData))
        formData[0].reset()
    })
}
socket.onerror = function(e){
    console.log("error", e)
}
socket.onclose = function(e){
    console.log("closed", e)
}


</script>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">



    <title>Real Time Chatting</title>
    {% include 'css.html' %}
    <script src="https://kit.fontawesome.com/debdddf209.js" crossorigin="anonymous"></script>
</head>
<body>
<nav class="navbar navbar-inverse">
        <div class="container-fluid">
          <div class="navbar-header">
            <a class="navbar-brand" href="{% url 'home' %}">Chat System</a>
          </div>
          <ul class="nav navbar-nav">
            <li class="active"><a href="{% url 'chat:online' %}">Online Users</a></li>
            
          </ul>
          <ul class="nav navbar-nav navbar-right">
              {% if user.is_authenticated %}
              
              <li><a href="{% url 'logout' %}"> logout  </a></li>
              <li><a> Welcome: {{user.get_username}} </a></li>
              {% else %}
            <li><a href="{% url 'login' %}"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
            {% endif %}
          </ul>
        </div>
      </nav>


<div class='container'>
    <div class='row border-bottom my-3 py-3'>
        <div class='col'>
            <h1 class='p-0 m-0'>Real Time Chatting</h1>
        </div>
    </div>
{% block content %}
{% endblock %}
</div>


{% include 'js.html' %}
{% block script %}
{% endblock %}

</body>
</html>

templates/css.html
<!-- Bootstrap CSS -->

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

templates/home.html
{% extends "base.html" %}

{% block content %}

<p class='lead'>Welcome Home</p>
{% endblock %}

templates/js.html
 <!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script
  src="//code.jquery.com/jquery-3.3.1.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
<script src="//stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>